# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pure < Formula
  desc "Pretty, minimal and fast zsh prompt"
  homepage "https://github.com/SijanC147/pure"
  url "https://github.com/SijanC147/pure/archive/refs/tags/v1.23.11.tar.gz"
  sha256 "c02c9ad7406ed27db70326e35e254fe08ce6bf0f24eb9f8142bb74dcb70fb708"
  license "MIT"

  depends_on "zsh" => :test
  depends_on "zsh-async"

  def install
    zsh_function.install "pure.zsh" => "prompt_pure_setup"
  end

  test do
    zsh_command = "setopt prompt_subst; autoload -U promptinit; promptinit && prompt -p pure"
    assert_match "❯", shell_output("zsh -c '#{zsh_command}'")
  end
end
