# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pure < Formula
  desc "Pretty, minimal and fast zsh prompt"
  homepage "https://github.com/SijanC147/pure"
  url "https://github.com/SijanC147/pure/archive/refs/tags/v1.23.7.tar.gz"
  sha256 "2c1f2ad22a9b6aea4c58d38a6863e3f8180456430a0ec8f43ec656fcdfaabeea"
  license "MIT"

  depends_on "zsh" => :test
  depends_on "zsh-async"

  def install
    zsh_function.install "pure.zsh" => "prompt_pure_setup"
  end

  test do
    zsh_command = "setopt prompt_subst; autoload -U promptinit; promptinit && prompt -p pure"
    assert_match "❯", shell_output("zsh -c '#{zsh_command}'")
  end
end
