# Generated by the verified Pure release workflow.
class Pure < Formula
  desc "Pretty, minimal and fast zsh prompt"
  homepage "https://github.com/SijanC147/pure"
  url "https://github.com/SijanC147/pure/archive/refs/tags/v1.28.3+20260906071326.tar.gz"
  version "1.28.3+20260906071326"
  sha256 "beabb273e31177c329f0efebbcd28f2bcb5e971893c7c0eb60d541a504041b4f"
  license "MIT"

  depends_on "zsh" => :test
  depends_on "zsh-async"

  def install
    zsh_function.install "pure.zsh" => "prompt_pure_setup"
  end

  test do
    command = "setopt prompt_subst; fpath=(#{zsh_function} #{Formula["zsh-async"].opt_share}/zsh/site-functions $fpath); autoload -U promptinit; promptinit; prompt -p pure"
    assert_match "❯", shell_output("zsh -fc '#{command}'")
  end
end
